CREATE DATABASE Pessoas_Tarde;

USE Pessoas_Tarde;

CREATE TABLE Pessoas (
	IdPessoa	INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(200) NOT NULL
);

CREATE TABLE Emails (
	IdEmail		INT PRIMARY KEY IDENTITY,
	Descricao	VARCHAR(200) NOT NULL,
	IdPessoa	INT FOREIGN KEY REFERENCES Pessoas (IdPessoa)
);

CREATE TABLE Telefones (
	IdTelefone		INT PRIMARY KEY IDENTITY,
	Descricao	VARCHAR(200) NOT NULL,
	IdPessoa	INT FOREIGN KEY REFERENCES Pessoas (IdPessoa)
);

CREATE TABLE CNH (
	IdCNH		INT PRIMARY KEY IDENTITY,
	Descricao	VARCHAR(200) NOT NULL,
	IdPessoa	INT FOREIGN KEY REFERENCES Pessoas (IdPessoa)
);

SELECT * FROM Pessoas;
SELECT * FROM Emails;
SELECT * FROM Telefones;
SELECT * FROM CNH;